// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package designate

import (
	"context"
)

const ZoneCount = `-- name: ZoneCount :one
SELECT COUNT(*) FROM zones
`

func (q *Queries) ZoneCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, ZoneCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
